# -*- coding: utf-8 -*-
# Part of StockSense. See LICENSE file for full copyright and licensing details.
"""StockSense - Export the stock movements to CSV.

The wizard behind *Stock Operations > Export Stock Movements to CSV* and the
*Export to CSV* entry of the Move History list (Actions menu). It selects the
``stock.move`` ledger on a period and on the StockSense filters (document type,
status, product, product category, source / destination location) and generates
the CSV file offered for download.

Design notes
------------
* Movements are searched with the rights of the user running the export, so the
  record rules (multi-company, multi-warehouse) are honoured: nobody exports
  movements they are not allowed to read.
* The generated file is stored in the ``file_data`` binary field of the
  transient wizard record and streamed by ``/web/content``, the standard Odoo
  way to serve a binary field. Nothing is written on the file system.
* The CSV is encoded as UTF-8 **with BOM** and every cell is quoted, so
  Microsoft Excel detects the encoding of the accented characters without an
  import step -- the natural companion of the native *Export* action, which
  covers the Excel (xlsx) and CSV formats of every list (see
  ``views/export_templates.xml``).
* The processed quantity is read through the StockSense ``operation_done_qty``
  field (``quantity_done`` on 16.0, ``quantity`` on 17.0), which keeps the
  export valid on both versions.

The period is applied on ``stock.move.date`` (the effective date of the
movement), interpreted in UTC, exactly like the ``date`` field is stored.
"""

import base64
import csv
import io
from datetime import datetime, time, timedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError

from ..models.stock_operations import OPERATION_TYPES


class StockExportWizard(models.TransientModel):
    """Export the stock movements of a period to a CSV file."""

    _name = 'stocksense.export.wizard'
    _description = 'StockSense Stock Movement Export'

    # ------------------------------------------------------------------
    # Criteria
    # ------------------------------------------------------------------
    date_from = fields.Date(
        string='From', required=True,
        default=lambda self: fields.Date.context_today(self).replace(day=1),
        help="First day of the exported period (included). Defaults to the "
             "first day of the current month.")
    date_to = fields.Date(
        string='To', required=True, default=fields.Date.context_today,
        help="Last day of the exported period (included). Defaults to today.")

    operation_type = fields.Selection(
        selection=[('all', 'All Documents')] + OPERATION_TYPES,
        string='Document Type', required=True, default='all',
        help="Receipts, deliveries or internal transfers. 'All Documents' "
             "exports the three operation types.")
    state = fields.Selection(
        selection=[
            ('all', 'All Statuses'),
            ('done', 'Done'),
            ('open', 'To Process'),
            ('cancel', 'Cancelled'),
        ],
        string='Status', required=True, default='all',
        help="Status of the movements to export. 'To Process' keeps the "
             "movements that are neither done nor cancelled.")

    product_id = fields.Many2one(
        'product.product', string='Product',
        help="Keep only the movements of this product.")
    product_categ_id = fields.Many2one(
        'product.category', string='Product Category',
        help="Keep only the movements of the products of this category.")
    location_id = fields.Many2one(
        'stock.location', string='From Location',
        domain="[('usage', 'in', ('internal', 'transit'))]",
        help="Keep only the movements leaving this location.")
    location_dest_id = fields.Many2one(
        'stock.location', string='To Location',
        domain="[('usage', 'in', ('internal', 'transit'))]",
        help="Keep only the movements arriving on this location.")
    move_ids = fields.Many2many(
        'stock.move', string='Selected Movements',
        help="Optional: the movements selected in the Move History list. They "
             "narrow the result down, the period and the other filters still "
             "apply.")
    company_id = fields.Many2one(
        'res.company', string='Company', required=True, index=True,
        default=lambda self: self.env.company,
        help="Company the exported movements belong to.")

    # ------------------------------------------------------------------
    # Result of the last export
    # ------------------------------------------------------------------
    file_data = fields.Binary(
        string='File', readonly=True, copy=False,
        help="CSV file generated by the last export.")
    file_name = fields.Char(
        string='File Name', readonly=True, copy=False)
    line_count = fields.Integer(
        string='Exported Movements', readonly=True, copy=False)

    @api.constrains('date_from', 'date_to')
    def _check_period(self):
        for wizard in self:
            if wizard.date_from and wizard.date_to \
                    and wizard.date_from > wizard.date_to:
                raise ValidationError(_(
                    "The first day of the period (%s) must be before its last "
                    "day (%s).", wizard.date_from, wizard.date_to))

    # ------------------------------------------------------------------
    # Selection of the movements
    # ------------------------------------------------------------------
    def _get_moves_domain(self):
        """Domain selecting the movements matching the criteria."""
        self.ensure_one()
        domain = [
            ('company_id', '=', self.company_id.id),
            ('date', '>=', datetime.combine(self.date_from, time.min)),
            ('date', '<', datetime.combine(
                self.date_to + timedelta(days=1), time.min)),
        ]
        if self.operation_type != 'all':
            domain.append(('operation_type', '=', self.operation_type))
        if self.state == 'done':
            domain.append(('state', '=', 'done'))
        elif self.state == 'open':
            domain.append(('state', 'not in', ('done', 'cancel')))
        elif self.state == 'cancel':
            domain.append(('state', '=', 'cancel'))
        if self.product_id:
            domain.append(('product_id', '=', self.product_id.id))
        if self.product_categ_id:
            domain.append(
                ('product_id.categ_id', '=', self.product_categ_id.id))
        if self.location_id:
            domain.append(('location_id', '=', self.location_id.id))
        if self.location_dest_id:
            domain.append(('location_dest_id', '=', self.location_dest_id.id))
        if self.move_ids:
            domain.append(('id', 'in', self.move_ids.ids))
        return domain

    def _get_moves(self):
        """Movements to export, in chronological order."""
        self.ensure_one()
        return self.env['stock.move'].search(
            self._get_moves_domain(), order='date, id')

    # ------------------------------------------------------------------
    # CSV generation
    # ------------------------------------------------------------------
    def _get_csv_headers(self):
        """Column headers, in the order of :meth:`_get_csv_row`."""
        return [
            _('Date'),
            _('Reference'),
            _('Source Document'),
            _('Document Type'),
            _('Status'),
            _('Product'),
            _('Product Category'),
            _('Lot/Serial Number'),
            _('From Location'),
            _('To Location'),
            _('Demand'),
            _('Processed'),
            _('Unit'),
            _('Stock Impact'),
            _('Company'),
        ]

    def _get_csv_row(self, move):
        """Return one stock movement as a row of the CSV file.

        A movement can be detailed on several move lines (several lots, several
        packages): the distinct lot / serial numbers are listed in one cell.
        """
        self.ensure_one()
        lots = move.move_line_ids.lot_id
        return [
            fields.Datetime.context_timestamp(
                self, move.date).strftime('%Y-%m-%d %H:%M:%S') if move.date else '',
            move.reference or '',
            move.origin or '',
            dict(OPERATION_TYPES).get(move.operation_type, ''),
            dict(move._fields['state'].selection).get(move.state, ''),
            move.product_id.display_name,
            move.product_id.categ_id.display_name,
            ', '.join(sorted(set(lots.mapped('name')))) if lots else '',
            move.location_id.display_name,
            move.location_dest_id.display_name,
            move.product_uom_qty,
            move.operation_done_qty,
            move.product_uom.display_name or '',
            move.operation_stock_impact,
            move.company_id.display_name,
        ]

    def _get_file_name(self):
        """Name of the file, e.g. ``stocksense_movements_20260101_20260131.csv``."""
        self.ensure_one()
        return 'stocksense_movements_%s_%s.csv' % (
            self.date_from.strftime('%Y%m%d'),
            self.date_to.strftime('%Y%m%d'),
        )

    @api.model
    def _sanitize_csv_cell(self, value):
        """Protect the text cells against spreadsheet formula injection.

        Spreadsheet applications read a cell starting with ``=``, ``+`` or
        ``-`` as a formula. The native Odoo export prefixes such *text* cells
        with a quote, StockSense does the same. Numbers are left untouched, so
        the negative stock impacts stay numeric in Excel.
        """
        if isinstance(value, str) and value.startswith(('=', '+', '-')):
            return "'" + value
        return value

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def action_export(self):
        """Generate the CSV file of the matching movements and download it."""
        self.ensure_one()
        moves = self._get_moves()
        if not moves:
            raise UserError(_(
                "No stock movement matches the selected criteria. Widen the "
                "period or clear a filter, then try again."))

        stream = io.StringIO(newline='')
        writer = csv.writer(
            stream, delimiter=',', quotechar='"', quoting=csv.QUOTE_ALL)
        writer.writerow([
            self._sanitize_csv_cell(header)
            for header in self._get_csv_headers()
        ])
        for move in moves:
            writer.writerow([
                self._sanitize_csv_cell(cell)
                for cell in self._get_csv_row(move)
            ])

        # ``utf-8-sig`` writes the BOM Microsoft Excel needs to detect the
        # encoding of the accented characters without an import step.
        self.write({
            'file_data': base64.b64encode(
                stream.getvalue().encode('utf-8-sig')),
            'file_name': self._get_file_name(),
            'line_count': len(moves),
        })
        return self.action_download()

    def action_download(self):
        """Stream the file generated by the last export."""
        self.ensure_one()
        if not self.file_data:
            raise UserError(_(
                "There is no file to download yet: click on 'Export to CSV' "
                "first."))
        return {
            'type': 'ir.actions.act_url',
            'name': _('Stock Movements'),
            # 'download' lets the client save the file without leaving the
            # wizard, so the generated file stays available in the dialog.
            'target': 'download',
            'url': '/web/content/?model=%s&id=%s&field=file_data'
                   '&filename_field=file_name&download=true'
                   % (self._name, self.id),
        }
